{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "6906fb72-47a7-4301-88b8-0f6df5fb0f9e",
   "metadata": {},
   "outputs": [],
   "source": [
    "1: \"Exception\"\n",
    "  An exception is python is an error that happens whenva program is running .\n",
    "    it can occur when the program encounters an unexpected situation,\n",
    "    such as dividing by zero or trying to access a file that donot exist...\n",
    "    \n",
    "  \"Syntax Error\" \n",
    " these are mistakes that happen when we write code. they occurs when we use\n",
    "    the wrony python syntax, such as forgetting colon or parenthesis...\n",
    "    \n",
    "    \n",
    ">The main difference between the two is that syntax errors prevent the\n",
    "  program from running at all\n",
    ">while exceptions happen during program execution.\n",
    ">Exceptions can be handled by your program using try-except blocks to avoid\n",
    " crashes and handle unexpected situations gracefully.\n",
    "    \n",
    "    \n",
    "    "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b8618a5e-48a7-486a-bf83-91f3f0a72024",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c34ac61a-2d33-4d9e-ad53-6d2e2ed9345b",
   "metadata": {},
   "outputs": [],
   "source": [
    "2: When an exception is not handled in Python, it can lead to crashes or\n",
    "unexpected behavior. One way to handle exceptions in Python is to use the\n",
    "\"logging\" module, which allows you to log error messages and other information \n",
    "about the state of your program.\n",
    "\n",
    "Example: it show what happens when an exception is not handled, with the help \n",
    "        of logging module we can handle exceptions\n",
    "    \n",
    "import logging\n",
    "\n",
    "def read_file(filename):\n",
    "    try:\n",
    "        with open(filename, 'r') as file:\n",
    "            content = file.read()\n",
    "            return content\n",
    "        except filenotfound as e:\n",
    "            logging.error(\"file not found: {}\".format(e))\n",
    "            \n",
    "def main():\n",
    "    content = read_file(\"example.txt\")\n",
    "    print(content)\n",
    "    \n",
    "if __name__ == \"__main__\"\n",
    "    main()\n",
    "    \n",
    "    \n",
    " output:\n",
    "    \n",
    "ERROR:root:File not found: [Errno 2] No such file or directory: \"example.txt\"\n",
    "\n",
    "    "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "5ed4e3c2-2744-424d-b8e7-2d25293df049",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "fd4ad154-3afb-4f8d-8615-76d2469dac8b",
   "metadata": {},
   "outputs": [],
   "source": [
    "3: In Python, we  can catch and handle exceptions using the 'try' and 'except'\n",
    "   statements.\n",
    "The try statement is used to enclose the code that may raise an exception,\n",
    "and the except statement is used to specify the code that should be executed\n",
    "if an exception is raised.\n",
    "\n",
    "\n",
    "Here an example that demonstrates how to use try and except statements to \n",
    "catch and handle exceptions in Python:\n",
    "\n",
    "    \n",
    "\n",
    "import logging\n",
    "logging.basicconfig(level=logging.ERROR)\n",
    "\n",
    "try:\n",
    "    x = int(input(\"enter a number\"))\n",
    "    y = int(input(\"entr another number\"))\n",
    "    result = x/y\n",
    "    logging.info(\"the result is: %s\" , result)\n",
    "except zerodivisionError:\n",
    "    logging.error(\"Error: division by zero\")\n",
    "except valueError :\n",
    "    logging.error(\"Error : invalid input\")\n",
    "except:\n",
    "    logging.error(\"Error: something went wrong\")\n",
    "    \n",
    "\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "54160d59-7c98-41f8-bdd5-7fa6934e3e4d",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "2ffd30e0-21ec-4c8b-a91b-1c63a8ee8520",
   "metadata": {},
   "outputs": [],
   "source": [
    "4: \n",
    "    \n",
    "1.\"try and else\"\n",
    "\n",
    "Example:\n",
    "\n",
    "try:\n",
    "    num = int(input(\"enter a number:\"))\n",
    "except ValueError:\n",
    "    print(\"invalid inout\")\n",
    "else:\n",
    "    print(\"yoy entered:\",num)\n",
    "\n",
    "\n",
    "In this example, I have use the try statement to try to convert user input\n",
    "into an integer using the int() function. If the user enters a non-numeric \n",
    "input, a ValueError exception is raised.\n",
    "\n",
    "The else statement is used to specify the code that should be executed if the\n",
    "try block is executed successfully, without raising any exceptions. In this\n",
    "case, I print a message indicating the number entered by the user.\n",
    "\n",
    "\"If the user enters a non-numeric input, the output will be:\"\n",
    "output: Enter a number: abc\n",
    "        \"Invalid input'\"\n",
    "\n",
    "Using the else statement in combination with try and except allows \n",
    "to separate error handling code from the main code block, and execute \n",
    "different code based on whether an exception was raised or not.\n",
    "\n",
    "\n",
    "\n",
    "2.\"finally\"\n",
    "\n",
    "Example:\n",
    "    \n",
    "try:\n",
    "    file = open(\"example.txt\",\"r\")\n",
    "    lines = file.readlines()\n",
    "    for line in lines:\n",
    "        print(line)\n",
    "except FileNotFoundError:\n",
    "    print(\"File Not Found\")\n",
    "finally:\n",
    "    file.close()\n",
    "\n",
    "\n",
    "In this example, I have use the try statement to attempt to open a file \n",
    "called \"example.txt\" for reading using the open() function. \n",
    "If the file is found, its contents are read into a list of lines using the\n",
    "\"readlines() method\".\n",
    "\n",
    "If the file is not found, a FileNotFoundError exception is raised, and the\n",
    "except block is executed, printing an error message indicating that the file\n",
    "was not found.\n",
    "\n",
    "If the file is found and opened successfully, the contents of the file are\n",
    "printed to the console. Regardless of whether an exception was raised or not,\n",
    "the file is closed after the contents have been read.\n",
    "\n",
    "  Using the \"finally\" block in combination with 'try and except' allows you to\n",
    "ensure that certain code is executed regardless of whether an exception was \n",
    "raised or not. This can be useful for tasks such as closing files or releasing\n",
    "resources that should always be cleaned up, even in the event of an error.\n",
    "\n",
    "\n",
    "3. \"Raise\"\n",
    "\n",
    "Example:\n",
    "    \n",
    "def divide(x, y):\n",
    "    if y == 0:\n",
    "        raise ValueError(\"Division by zero is not allowed!\")\n",
    "    return x / y\n",
    "\n",
    "try:\n",
    "    result = divide(10, 0)\n",
    "except ValueError as e:\n",
    "    print(e)\n",
    "else:\n",
    "    print(result)\n",
    "\n",
    "\n",
    " In this example, I define a function called divide() that takes two\n",
    "arguments and returns their quotient. I use an if statement to check whether\n",
    "the second argument y is equal to zero. If it is, I raise a ValueError \n",
    "exception with a message indicating that division by zero is not allowed.\n",
    "\n",
    "then i use a try statement to call the divide() function with arguments\n",
    "10 and 0. Since the second argument is 0, the ValueError exception is raised.\n",
    "The except statement catches the ValueError exception and prints the error \n",
    "message passed to the raise statement.\n",
    "The except statement catches the 'ValueError' exception and prints the error \n",
    "message passed to the raise statement.\n",
    "\n",
    "If the second argument to divide() is a non-zero value, the quotient is \n",
    "calculated and returned, and the else block is executed, printing the result\n",
    "to the console.\n",
    "\n",
    "Using the raise statement allows us to raise our own exceptions in Python,\n",
    "with a custom message or other information. This can be useful when we need \n",
    "to handle specific error conditions that are not covered by the built-in\n",
    "Python exceptions.\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d19f4140-5f63-40f4-a174-34f8a03271aa",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "2573035a-b82c-4c38-82e0-ae372f33ad24",
   "metadata": {},
   "outputs": [],
   "source": [
    "5:\n",
    "    In Python, custom exceptions are user-defined exception classes that we \n",
    "can create to raise and handle specific types of errors that are specific to\n",
    "our code. We need custom exceptions to provide more specific error messages to\n",
    "the user, which can help them quickly identify the source of the problem and\n",
    "take appropriate actions to resolve the issue...\n",
    "\n",
    "Example:\n",
    "    \n",
    "class InvalidInputException(Exception):\n",
    "    pass\n",
    "\n",
    "def divide(num1, num2):\n",
    "    if num2 == 0:\n",
    "        raise InvalidInputException(\"The second number cannot be zero.\")\n",
    "    else:\n",
    "        return num1 / num2\n",
    "\n",
    "try:\n",
    "    result = divide(10, 0)\n",
    "except InvalidInputException as e:\n",
    "    print(e)\n",
    "\n",
    "\n",
    "\n",
    "In this example, I have define a custom exception called \"InvalidInputException\"\n",
    "that inherits from the built-in Exception class.\n",
    " then i define a function called divide() that takes two numbers as arguments\n",
    "and returns their division result. However, if the second number is zero,\n",
    "i raise the InvalidInputException with a message indicating that the\n",
    "second number cannot be zero.\n",
    "\n",
    "then i call the divide() function with two arguments: 10 and 0,\n",
    "which triggers the InvalidInputException and\n",
    "prints the error message to the console.\n",
    "\n",
    "By using custom exceptions, we can provide more specific and informative \n",
    "error messages that can help users understand what went wrong and take \n",
    "appropriate actions to fix the problem...\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "96de9bb9-d6fd-4d2c-afae-5bfc00a56dbe",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "976e4532-870e-4d36-be8b-e66a23d5d9f9",
   "metadata": {},
   "outputs": [],
   "source": [
    "6: here we are creating the custom exception class\n",
    "\n",
    "Example:\n",
    "class EmptyListException(Exception):\n",
    "    def __init__(self, message=\"List is empty.\"):\n",
    "        self.message = message\n",
    "        super().__init__(self.message)\n",
    "\n",
    "def get_first_element(my_list):\n",
    "    if len(my_list) == 0:\n",
    "        raise EmptyListException()\n",
    "    return my_list[0]\n",
    "\n",
    "try:\n",
    "    my_list = []\n",
    "    first_element = get_first_element(my_list)\n",
    "except EmptyListException as e:\n",
    "    print(e)\n",
    "\n",
    "    \n",
    "In this example, I have define a custom exception class called \n",
    "\"EmptyListException\" that inherits from the built-in Exception class.\n",
    "We override the __init__() method to provide a default error message \n",
    "if none is provided.\n",
    "\n",
    "then i define a get_first_element() function that takes a list as an argument\n",
    "and returns its first element. However, before returning the first element, \n",
    "check if the list is empty. If it is, raise the 'EmptyListException'.\n",
    "\n",
    "In the try block, i have create an empty list and call the\n",
    "'get_first_element()' function with this list. Since the list is empty, \n",
    "this triggers the EmptyListException and prints the error message to the\n",
    "console using the except block.\n",
    "\n",
    "By using custom exceptions, we can handle specific errors that may occur in\n",
    "our code and provide helpful error messages to the user. This can make our \n",
    "code more user-friendly and easier to debug.\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "6e388fbb-a843-4175-8470-3e3432099aa9",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
